name: Run random client pairs

on:
  workflow_dispatch:

concurrency:
  group: "random-docker-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  run_assertoor:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - "kurtosis-config/test1.yaml"
        pairs:
        #- "lighthouse-reth,teku-geth,prysm-nethermind"
        #- "lighthouse-geth,teku-nethermind,lodestar-erigon"
        #- "prysm-nethermind,teku-erigon,nimbus-besu"
        #- "prysm-geth,teku-besu,lodestar-reth"
        #- "nimbus-reth,prysm-geth,lighthouse-nethermind"
        #- "lodestar-geth,prysm-besu,nimbus-erigon"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
       
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Run Tests for ${{ matrix.pairs }}
      id: run-test
      uses: ./.github/actions/run-test-docker
      with:
        ## Variables
        pairs: ${{ matrix.pairs }}
        config: ${{ matrix.config }}
