name: Run random client pairs

on:
  workflow_dispatch:

concurrency:
  group: "random-docker-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  run_assertoor:
    uses: ./.github/workflows/_shared-run-docker.yaml
    strategy:
      fail-fast: false
      matrix:
        config:
        - "kurtosis-config/test1.yaml"
        pairs:
        #- "lighthouse-reth,teku-geth,prysm-nethermind"
        #- "lighthouse-geth,teku-nethermind,lodestar-erigon"
        #- "prysm-nethermind,teku-erigon,nimbus-besu"
        #- "prysm-geth,teku-besu,lodestar-reth"
        #- "nimbus-reth,prysm-geth,lighthouse-nethermind"
        #- "lodestar-geth,prysm-besu,nimbus-erigon"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
        - "lighthouse-random,random,random"
    with:
      pairs: ${{ matrix.pairs }}
      config: ${{ matrix.config }}
